version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps

  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.16.3 # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:4.2.0
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: alias monogd
          command: 'alias mongod=''docker run --name mongo --rm mongo:4.2.0'''
      - run:
          name: install mongodb
          command: 'sudo wget https://repo.mongodb.org/apt/ubuntu/dists/bionic/mongodb-org/4.2/multiverse/binary-amd64/mongodb-org_4.2.0_amd64.deb'
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: give all repos
          command: 'npm run sync-modules'
      - run:
          name: install-npm
          command: 'npm install'
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: npm init db
          command: 'npm run init'
      - run:
          name: npm start
          command: 'npm start'
          background: true
      - run:
          name: wait until up
          command: 'sleep 60'
      - run: 
          name: test
          command: curl -i http://localhost:3001/gp-admin